### ISSUE TITLE
权限验证是个伪验证啊

### ISSUE THREAD

**Issue by justmd5** [15225220191/VueAdmin#1]
1.登录认证验证前后端都没有交互；
2.api请求接口都不带上认证标示的；
3.既然是做通用型后台，前端根据权限访问控制还是得有（这个更是没影）。

综上，这项目离线上使用还差蛮远的。

**Comment by 15225220191** [comment]
1、首先，这个项目刚开始写，确实存在很多问题，后续这些都会进行补充；同时也希望大家发现问题能及时提出并完善，希望各位都能参与这个项目的迭代。
2、登录认证这块没有做是因为想着准备加入一个单点登录功能，验证交互想放在另外的中心服务器上。
3、发布这个项目的主要目的还是想跟大家多学习多交流，希望自己能借此不断进步。


综上：以学习为主，希望各位大佬不吝赐教！！！




------------------ 原始邮件 ------------------
发件人: "独步弈城"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 上午9:50
收件人: "15225220191/VueAdmin"<VueAdmin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [15225220191/VueAdmin] 权限验证是个伪验证啊 (#1)




1.登录认证验证前后端都没有交互；
 2.api请求接口都不带上认证标示的；
 3.既然是做通用型后台，前端根据权限访问控制还是得有（这个更是没影）。
 
综上，这项目离线上使用还差蛮远的。
